pages = [{"l":"index.html#","e":false,"i":"","n":"Scothello","t":"Scothello","d":"","k":"static","x":""},
{"l":"scothello.html#","e":false,"i":"","n":"scothello","t":"scothello","d":"","k":"package","x":""},
{"l":"scothello.html#main-94c","e":false,"i":"","n":"main","t":"main(): Unit","d":"scothello","k":"def","x":""},
{"l":"scothello.html#rootScene-0","e":false,"i":"","n":"rootScene","t":"rootScene: Scene","d":"scothello","k":"given","x":""},
{"l":"scothello/controllers.html#","e":false,"i":"","n":"scothello.controllers","t":"scothello.controllers","d":"","k":"package","x":""},
{"l":"scothello/controllers/home.html#","e":false,"i":"","n":"scothello.controllers.home","t":"scothello.controllers.home","d":"","k":"package","x":""},
{"l":"scothello/controllers/home/HomeController.html#","e":false,"i":"","n":"HomeController","t":"HomeController extends Controller","d":"scothello.controllers.home","k":"trait","x":""},
{"l":"scothello/controllers/home/HomeController$.html#","e":false,"i":"","n":"HomeController","t":"HomeController","d":"scothello.controllers.home","k":"object","x":""},
{"l":"scothello/controllers/home/HomeController$.html#apply-fffff424","e":false,"i":"","n":"apply","t":"apply(requirements: Requirements[HomeView]): HomeController","d":"scothello.controllers.home.HomeController","k":"def","x":""},
{"l":"scothello/controllers/BaseController.html#","e":false,"i":"","n":"BaseController","t":"BaseController[V <: View](requirements: Requirements[V]) extends Controller, Dependencies[V]","d":"scothello.controllers","k":"class","x":""},
{"l":"scothello/controllers/BaseController.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.controllers.BaseController","k":"val","x":""},
{"l":"scothello/controllers/Controller.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"scothello.controllers","k":"trait","x":""},
{"l":"scothello/controllers/Controller.html#state-0","e":false,"i":"","n":"state","t":"state: GameState","d":"scothello.controllers.Controller","k":"def","x":""},
{"l":"scothello/controllers/Controller$.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"scothello.controllers","k":"object","x":""},
{"l":"scothello/controllers/Controller$.html#Factory-0","e":false,"i":"","n":"Factory","t":"Factory[V <: View, C <: Controller] = Requirements[V] => C","d":"scothello.controllers.Controller","k":"type","x":""},
{"l":"scothello/controllers/Controller$$Dependencies.html#","e":false,"i":"","n":"Dependencies","t":"Dependencies[V <: View](requirements: Requirements[V]) extends Controller","d":"scothello.controllers.Controller","k":"trait","x":""},
{"l":"scothello/controllers/Controller$$Dependencies.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.controllers.Controller.Dependencies","k":"def","x":""},
{"l":"scothello/controllers/Controller$$Dependencies.html#view-0","e":false,"i":"","n":"view","t":"view: V","d":"scothello.controllers.Controller.Dependencies","k":"def","x":""},
{"l":"scothello/controllers/Controller$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider[C <: Controller]","d":"scothello.controllers.Controller","k":"trait","x":""},
{"l":"scothello/controllers/Controller$$Provider.html#controller-0","e":false,"i":"","n":"controller","t":"controller: C","d":"scothello.controllers.Controller.Provider","k":"def","x":""},
{"l":"scothello/controllers/Controller$$Requirements.html#","e":false,"i":"","n":"Requirements","t":"Requirements[V <: View] extends Provider, Provider[V]","d":"scothello.controllers.Controller","k":"trait","x":""},
{"l":"scothello/controllers/EmptyController.html#","e":false,"i":"","n":"EmptyController","t":"EmptyController[V <: View](requirements: Requirements[V]) extends BaseController[V]","d":"scothello.controllers","k":"class","x":""},
{"l":"scothello/controllers/ReactiveModelWrapper.html#","e":false,"i":"","n":"ReactiveModelWrapper","t":"ReactiveModelWrapper(view: => View, model: Model) extends Model","d":"scothello.controllers","k":"class","x":""},
{"l":"scothello/model.html#","e":false,"i":"","n":"scothello.model","t":"scothello.model","d":"","k":"package","x":""},
{"l":"scothello/model/board.html#","e":false,"i":"","n":"scothello.model.board","t":"scothello.model.board","d":"","k":"package","x":""},
{"l":"scothello/model/board/Board.html#","e":false,"i":"","n":"Board","t":"Board(rows: Int, cols: Int) extends TiledBoard","d":"scothello.model.board","k":"class","x":""},
{"l":"scothello/model/board/Tile.html#","e":false,"i":"","n":"Tile","t":"Tile","d":"scothello.model.board","k":"trait","x":""},
{"l":"scothello/model/board/Tile.html#col-0","e":false,"i":"","n":"col","t":"col: Int","d":"scothello.model.board.Tile","k":"def","x":""},
{"l":"scothello/model/board/Tile.html#row-0","e":false,"i":"","n":"row","t":"row: Int","d":"scothello.model.board.Tile","k":"def","x":""},
{"l":"scothello/model/board/Tile$.html#","e":false,"i":"","n":"Tile","t":"Tile","d":"scothello.model.board","k":"object","x":""},
{"l":"scothello/model/board/Tile$.html#apply-fffff0ac","e":false,"i":"","n":"apply","t":"apply(row: Int, col: Int): Tile","d":"scothello.model.board.Tile","k":"def","x":""},
{"l":"scothello/model/board/TiledBoard.html#","e":false,"i":"","n":"TiledBoard","t":"TiledBoard(val rows: Int, val cols: Int)","d":"scothello.model.board","k":"class","x":""},
{"l":"scothello/model/board/TiledBoard.html#cols-0","e":false,"i":"","n":"cols","t":"cols: Int","d":"scothello.model.board.TiledBoard","k":"val","x":""},
{"l":"scothello/model/board/TiledBoard.html#rows-0","e":false,"i":"","n":"rows","t":"rows: Int","d":"scothello.model.board.TiledBoard","k":"val","x":""},
{"l":"scothello/model/board/TiledBoard.html#tiles-0","e":false,"i":"","n":"tiles","t":"tiles: Set[Tile]","d":"scothello.model.board.TiledBoard","k":"val","x":""},
{"l":"scothello/model/components.html#","e":false,"i":"","n":"scothello.model.components","t":"scothello.model.components","d":"","k":"package","x":""},
{"l":"scothello/model/components.html#Scores-0","e":false,"i":"","n":"Scores","t":"Scores = Map[Player, Int]","d":"scothello.model.components","k":"type","x":""},
{"l":"scothello/model/components/Scores$.html#","e":false,"i":"","n":"Scores","t":"Scores","d":"scothello.model.components","k":"object","x":""},
{"l":"scothello/model/components/Scores$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Scores","d":"scothello.model.components.Scores","k":"def","x":""},
{"l":"scothello/model/components/Scores$.html#initialize-fffff010","e":false,"i":"","n":"initialize","t":"initialize(players: Pair[Player]): Scores","d":"scothello.model.components.Scores","k":"def","x":""},
{"l":"scothello/model/game.html#","e":false,"i":"","n":"scothello.model.game","t":"scothello.model.game","d":"","k":"package","x":""},
{"l":"scothello/model/game/config.html#","e":false,"i":"","n":"scothello.model.game.config","t":"scothello.model.game.config","d":"","k":"package","x":""},
{"l":"scothello/model/game/config/Player.html#","e":false,"i":"","n":"Player","t":"Player","d":"scothello.model.game.config","k":"trait","x":""},
{"l":"scothello/model/game/config/Player.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"scothello.model.game.config.Player","k":"def","x":""},
{"l":"scothello/model/game/config/Player$.html#","e":false,"i":"","n":"Player","t":"Player","d":"scothello.model.game.config","k":"object","x":""},
{"l":"scothello/model/game/config/Player$.html#apply-fffff54c","e":false,"i":"","n":"apply","t":"apply(name: String): Player","d":"scothello.model.game.config.Player","k":"def","x":""},
{"l":"scothello/model/game/config/Player$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Player","d":"scothello.model.game.config.Player","k":"val","x":""},
{"l":"scothello/model/game/state.html#","e":false,"i":"","n":"scothello.model.game.state","t":"scothello.model.game.state","d":"","k":"package","x":""},
{"l":"scothello/model/game/state/GameState.html#","e":false,"i":"","n":"GameState","t":"GameState(players: Option[Pair[Player]], board: Board, turn: Turn, playerScores: Scores, isOver: Boolean, winner: Option[Player])","d":"scothello.model.game.state","k":"class","x":""},
{"l":"scothello/model/game/state/GameState$.html#","e":false,"i":"","n":"GameState","t":"GameState","d":"scothello.model.game.state","k":"object","x":""},
{"l":"scothello/model/game/state/GameState$.html#apply-cfc","e":false,"i":"","n":"apply","t":"apply(): GameState","d":"scothello.model.game.state.GameState","k":"def","x":""},
{"l":"scothello/model/game/Turn.html#","e":false,"i":"","n":"Turn","t":"Turn","d":"scothello.model.game","k":"trait","x":""},
{"l":"scothello/model/game/Turn.html#number-0","e":false,"i":"","n":"number","t":"number: Int","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn.html#player-0","e":false,"i":"","n":"player","t":"player: Player","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$.html#","e":false,"i":"","n":"Turn","t":"Turn","d":"scothello.model.game","k":"object","x":""},
{"l":"scothello/model/game/Turn$.html#apply-495","e":false,"i":"","n":"apply","t":"apply(number: Int, player: Player): Turn","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Turn","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$.html#initial-81c","e":false,"i":"","n":"initial","t":"initial(player: Player): Turn","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$$Empty.html#","e":false,"i":"","n":"Empty","t":"Empty extends Turn","d":"scothello.model.game.Turn","k":"trait","x":""},
{"l":"scothello/model/game/Turn$$Empty.html#number-0","e":false,"i":"","n":"number","t":"number: Int","d":"scothello.model.game.Turn.Empty","k":"def","x":""},
{"l":"scothello/model/game/Turn$$Empty.html#player-0","e":false,"i":"","n":"player","t":"player: Player","d":"scothello.model.game.Turn.Empty","k":"def","x":""},
{"l":"scothello/model/game/Turn$$EmptyTurn$.html#","e":false,"i":"","n":"EmptyTurn","t":"EmptyTurn extends Empty","d":"scothello.model.game.Turn","k":"object","x":""},
{"l":"scothello/model/Model.html#","e":false,"i":"","n":"Model","t":"Model","d":"scothello.model","k":"trait","x":""},
{"l":"scothello/model/Model.html#state-0","e":false,"i":"","n":"state","t":"state: GameState","d":"scothello.model.Model","k":"def","x":""},
{"l":"scothello/model/Model.html#update-c9d","e":false,"i":"","n":"update","t":"update(u: GameState => GameState): Unit","d":"scothello.model.Model","k":"def","x":""},
{"l":"scothello/model/Model$.html#","e":false,"i":"","n":"Model","t":"Model","d":"scothello.model","k":"object","x":""},
{"l":"scothello/model/Model$.html#apply-5d7","e":false,"i":"","n":"apply","t":"apply(initialState: GameState): Model","d":"scothello.model.Model","k":"def","x":""},
{"l":"scothello/model/Model$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"scothello.model.Model","k":"trait","x":""},
{"l":"scothello/model/Model$$Provider.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.model.Model.Provider","k":"def","x":""},
{"l":"scothello/model/Model$$Requirements.html#","e":false,"i":"","n":"Requirements","t":"Requirements","d":"scothello.model.Model","k":"trait","x":""},
{"l":"scothello/utils.html#","e":false,"i":"","n":"scothello.utils","t":"scothello.utils","d":"","k":"package","x":""},
{"l":"scothello/utils/Pair.html#","e":false,"i":"","n":"Pair","t":"Pair[A](_1: A, _2: A)","d":"scothello.utils","k":"class","x":""},
{"l":"scothello/utils/Pair.html#map-66b","e":false,"i":"","n":"map","t":"map[B](f: A => B): Seq[B]","d":"scothello.utils.Pair","k":"def","x":""},
{"l":"scothello/utils/Pair$.html#","e":false,"i":"","n":"Pair","t":"Pair","d":"scothello.utils","k":"object","x":""},
{"l":"scothello/utils/Pair$.html#tupleToPair-fffff14b","e":false,"i":"","n":"tupleToPair","t":"tupleToPair[A](tuple: (A, A)): Pair[A]","d":"scothello.utils.Pair","k":"def","x":""},
{"l":"scothello/views.html#","e":false,"i":"","n":"scothello.views","t":"scothello.views","d":"","k":"package","x":""},
{"l":"scothello/views/home.html#","e":false,"i":"","n":"scothello.views.home","t":"scothello.views.home","d":"","k":"package","x":""},
{"l":"scothello/views/home/HomeView.html#","e":false,"i":"","n":"HomeView","t":"HomeView extends View","d":"scothello.views.home","k":"trait","x":""},
{"l":"scothello/views/home/HomeView$.html#","e":false,"i":"","n":"HomeView","t":"HomeView","d":"scothello.views.home","k":"object","x":""},
{"l":"scothello/views/home/HomeView$.html#apply-3be","e":false,"i":"","n":"apply","t":"apply(scene: Scene, requirements: Requirements[HomeController]): HomeView","d":"scothello.views.home.HomeView","k":"def","x":""},
{"l":"scothello/views/BaseScalaFXView.html#","e":false,"i":"","n":"BaseScalaFXView","t":"BaseScalaFXView[C <: Controller](scene: Scene, requirements: Requirements[C]) extends BaseView[C], ScalaFXView","d":"scothello.views","k":"class","x":""},
{"l":"scothello/views/BaseView.html#","e":false,"i":"","n":"BaseView","t":"BaseView[C <: Controller](val requirements: Requirements[C]) extends View, Dependencies[C]","d":"scothello.views","k":"class","x":""},
{"l":"scothello/views/BaseView.html#requirements-0","e":false,"i":"","n":"requirements","t":"requirements: Requirements[C]","d":"scothello.views.BaseView","k":"val","x":""},
{"l":"scothello/views/GamePage.html#","e":false,"i":"","n":"GamePage","t":"GamePage[C <: Controller, V <: View](val model: Model, val pageFactory: PageFactory[C, V]) extends Requirements, Requirements[C], Requirements[V]","d":"scothello.views","k":"trait","x":""},
{"l":"scothello/views/GamePage.html#controller-0","e":false,"i":"","n":"controller","t":"controller: C","d":"scothello.views.GamePage","k":"val","x":""},
{"l":"scothello/views/GamePage.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.views.GamePage","k":"val","x":""},
{"l":"scothello/views/GamePage.html#pageFactory-0","e":false,"i":"","n":"pageFactory","t":"pageFactory: PageFactory[C, V]","d":"scothello.views.GamePage","k":"val","x":""},
{"l":"scothello/views/GamePage.html#view-0","e":false,"i":"","n":"view","t":"view: V","d":"scothello.views.GamePage","k":"val","x":""},
{"l":"scothello/views/GamePage$.html#","e":false,"i":"","n":"GamePage","t":"GamePage","d":"scothello.views","k":"object","x":""},
{"l":"scothello/views/GamePage$.html#apply-f7b","e":false,"i":"","n":"apply","t":"apply[C <: Controller, V <: View](model: Model, pageFactory: PageFactory[C, V]): GamePage[C, V]","d":"scothello.views.GamePage","k":"def","x":""},
{"l":"scothello/views/PageFactory.html#","e":false,"i":"","n":"PageFactory","t":"PageFactory[C <: Controller, V <: View]","d":"scothello.views","k":"trait","x":""},
{"l":"scothello/views/PageFactory.html#controllerFactory-0","e":false,"i":"","n":"controllerFactory","t":"controllerFactory: V => C","d":"scothello.views.PageFactory","k":"def","x":""},
{"l":"scothello/views/PageFactory.html#viewFactory-0","e":false,"i":"","n":"viewFactory","t":"viewFactory: C => V","d":"scothello.views.PageFactory","k":"def","x":""},
{"l":"scothello/views/PageFactory$.html#","e":false,"i":"","n":"PageFactory","t":"PageFactory","d":"scothello.views","k":"object","x":""},
{"l":"scothello/views/PageFactory$.html#apply-fffffe18","e":false,"i":"","n":"apply","t":"apply[C <: Controller, V <: View](_viewFactory: C => V, _controllerFactory: V => C): PageFactory[C, V]","d":"scothello.views.PageFactory","k":"def","x":""},
{"l":"scothello/views/ScalaFXPageFactory$.html#","e":false,"i":"","n":"ScalaFXPageFactory","t":"ScalaFXPageFactory","d":"scothello.views","k":"object","x":""},
{"l":"scothello/views/ScalaFXPageFactory$.html#apply-5e7","e":false,"i":"","n":"apply","t":"apply[C <: Controller, V <: View](scalaFXViewFactory: C => V, _controllerFactory: V => C)(using rootScene: Scene): PageFactory[C, V]","d":"scothello.views.ScalaFXPageFactory","k":"def","x":""},
{"l":"scothello/views/ScalaFXView.html#","e":false,"i":"","n":"ScalaFXView","t":"ScalaFXView(val scene: Scene) extends View","d":"scothello.views","k":"trait","x":""},
{"l":"scothello/views/ScalaFXView.html#parent-0","e":false,"i":"","n":"parent","t":"parent: Parent","d":"scothello.views.ScalaFXView","k":"def","x":""},
{"l":"scothello/views/ScalaFXView.html#reactiveState-0","e":false,"i":"","n":"reactiveState","t":"reactiveState: ObjectProperty[GameState]","d":"scothello.views.ScalaFXView","k":"def","x":""},
{"l":"scothello/views/ScalaFXView.html#scene-0","e":false,"i":"","n":"scene","t":"scene: Scene","d":"scothello.views.ScalaFXView","k":"val","x":""},
{"l":"scothello/views/ScalaFXView$.html#","e":false,"i":"","n":"ScalaFXView","t":"ScalaFXView","d":"scothello.views","k":"object","x":""},
{"l":"scothello/views/ScalaFXView$.html#Factory-0","e":false,"i":"","n":"Factory","t":"Factory[C <: Controller, V <: View] = (Scene, Requirements[C]) => V","d":"scothello.views.ScalaFXView","k":"type","x":""},
{"l":"scothello/views/View.html#","e":false,"i":"","n":"View","t":"View","d":"scothello.views","k":"trait","x":""},
{"l":"scothello/views/View.html#hide-94c","e":false,"i":"","n":"hide","t":"hide(): Unit","d":"scothello.views.View","k":"def","x":""},
{"l":"scothello/views/View.html#show-94c","e":false,"i":"","n":"show","t":"show(): Unit","d":"scothello.views.View","k":"def","x":""},
{"l":"scothello/views/View.html#state-0","e":false,"i":"","n":"state","t":"state: GameState","d":"scothello.views.View","k":"def","x":""},
{"l":"scothello/views/View.html#updateState-b48","e":false,"i":"","n":"updateState","t":"updateState(state: GameState): Unit","d":"scothello.views.View","k":"def","x":""},
{"l":"scothello/views/View$.html#","e":false,"i":"","n":"View","t":"View","d":"scothello.views","k":"object","x":""},
{"l":"scothello/views/View$.html#Factory-0","e":false,"i":"","n":"Factory","t":"Factory[C <: Controller, V <: View] = Requirements[C] => V","d":"scothello.views.View","k":"type","x":""},
{"l":"scothello/views/View$$Dependencies.html#","e":false,"i":"","n":"Dependencies","t":"Dependencies[C <: Controller](requirements: Requirements[C]) extends View","d":"scothello.views.View","k":"trait","x":""},
{"l":"scothello/views/View$$Dependencies.html#controller-0","e":false,"i":"","n":"controller","t":"controller: C","d":"scothello.views.View.Dependencies","k":"def","x":""},
{"l":"scothello/views/View$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider[V <: View]","d":"scothello.views.View","k":"trait","x":""},
{"l":"scothello/views/View$$Provider.html#view-0","e":false,"i":"","n":"view","t":"view: V","d":"scothello.views.View.Provider","k":"def","x":""},
{"l":"scothello/views/View$$Requirements.html#","e":false,"i":"","n":"Requirements","t":"Requirements[C <: Controller] extends Provider[C]","d":"scothello.views.View","k":"trait","x":""},
{"l":"scothello/Pages.html#","e":false,"i":"","n":"Pages","t":"Pages(val pageFactory: PageFactory[_, _])","d":"scothello","k":"enum","x":""},
{"l":"scothello/Pages.html#Home-0","e":false,"i":"","n":"Home","t":"Home extends Pages","d":"scothello.Pages","k":"case","x":""},
{"l":"scothello/ScothelloApp$.html#","e":false,"i":"","n":"ScothelloApp","t":"ScothelloApp extends JFXApp3","d":"scothello","k":"object","x":""},
{"l":"scothello/ScothelloFXApp$.html#","e":false,"i":"","n":"ScothelloFXApp","t":"ScothelloFXApp extends JFXApp3","d":"scothello","k":"object","x":""},
{"l":"scothello/ScothelloFXApp$.html#postInitAction-0","e":false,"i":"","n":"postInitAction","t":"postInitAction: () => Unit","d":"scothello.ScothelloFXApp","k":"var","x":""},
{"l":"scothello/ScothelloFXApp$.html#rootScene-0","e":false,"i":"","n":"rootScene","t":"rootScene: Scene","d":"scothello.ScothelloFXApp","k":"val","x":""},
{"l":"scothello/ScothelloGame.html#","e":false,"i":"","n":"ScothelloGame","t":"ScothelloGame","d":"scothello","k":"trait","x":""},
{"l":"scothello/ScothelloGame.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.ScothelloGame","k":"val","x":""},
{"l":"scothello/ScothelloGame.html#pages-0","e":false,"i":"","n":"pages","t":"pages: Map[Pages, GamePage[_, _]]","d":"scothello.ScothelloGame","k":"val","x":""},
{"l":"scothello/ScothelloGame$.html#","e":false,"i":"","n":"ScothelloGame","t":"ScothelloGame","d":"scothello","k":"object","x":""},
{"l":"scothello/ScothelloGame$.html#apply-896","e":false,"i":"","n":"apply","t":"apply(pagesFactories: Map[Pages, PageFactory[_, _]]): ScothelloGame","d":"scothello.ScothelloGame","k":"def","x":""},
{"l":"scothello/ScothelloGameManager$.html#","e":false,"i":"","n":"ScothelloGameManager","t":"ScothelloGameManager","d":"scothello","k":"object","x":""},
{"l":"scothello/ScothelloGameManager$.html#navigateTo-fffff9bf","e":false,"i":"","n":"navigateTo","t":"navigateTo(page: Pages): Unit","d":"scothello.ScothelloGameManager","k":"def","x":""},
{"l":"scothello/ScothelloGameManager$.html#startGame-94c","e":false,"i":"","n":"startGame","t":"startGame(): Unit","d":"scothello.ScothelloGameManager","k":"def","x":""},
{"l":"scothello/main.html#","e":false,"i":"","n":"main","t":"main","d":"scothello","k":"class","x":""}];