pages = [{"l":"index.html#","e":false,"i":"","n":"Scothello","t":"Scothello","d":"","k":"static","x":""},
{"l":"scothello.html#","e":false,"i":"","n":"scothello","t":"scothello","d":"","k":"package","x":""},
{"l":"scothello.html#main-94c","e":false,"i":"","n":"main","t":"main(): Unit","d":"scothello","k":"def","x":""},
{"l":"scothello/controller.html#","e":false,"i":"","n":"scothello.controller","t":"scothello.controller","d":"","k":"package","x":""},
{"l":"scothello/controller/game.html#","e":false,"i":"","n":"scothello.controller.game","t":"scothello.controller.game","d":"","k":"package","x":""},
{"l":"scothello/controller/game/GameController.html#","e":false,"i":"","n":"GameController","t":"GameController extends Controller","d":"scothello.controller.game","k":"trait","x":""},
{"l":"scothello/controller/game/GameController.html#calculateAllowedPos-94c","e":false,"i":"","n":"calculateAllowedPos","t":"calculateAllowedPos(): Unit","d":"scothello.controller.game.GameController","k":"def","x":""},
{"l":"scothello/controller/game/GameController.html#flipPawns-718","e":false,"i":"","n":"flipPawns","t":"flipPawns(tile: Tile): Unit","d":"scothello.controller.game.GameController","k":"def","x":""},
{"l":"scothello/controller/game/GameController.html#nextTurn-94c","e":false,"i":"","n":"nextTurn","t":"nextTurn(): Unit","d":"scothello.controller.game.GameController","k":"def","x":""},
{"l":"scothello/controller/game/GameController.html#placePawn-718","e":false,"i":"","n":"placePawn","t":"placePawn(tile: Tile): Unit","d":"scothello.controller.game.GameController","k":"def","x":""},
{"l":"scothello/controller/game/GameController$.html#","e":false,"i":"","n":"GameController","t":"GameController","d":"scothello.controller.game","k":"object","x":""},
{"l":"scothello/controller/game/GameController$.html#apply-fffffc20","e":false,"i":"","n":"apply","t":"apply(requirements: Requirements[GameView]): GameController","d":"scothello.controller.game.GameController","k":"def","x":""},
{"l":"scothello/controller/home.html#","e":false,"i":"","n":"scothello.controller.home","t":"scothello.controller.home","d":"","k":"package","x":""},
{"l":"scothello/controller/home/HomeController.html#","e":false,"i":"","n":"HomeController","t":"HomeController extends Controller","d":"scothello.controller.home","k":"trait","x":""},
{"l":"scothello/controller/home/HomeController$.html#","e":false,"i":"","n":"HomeController","t":"HomeController","d":"scothello.controller.home","k":"object","x":""},
{"l":"scothello/controller/home/HomeController$.html#apply-40","e":false,"i":"","n":"apply","t":"apply(requirements: Requirements[HomeView]): HomeController","d":"scothello.controller.home.HomeController","k":"def","x":""},
{"l":"scothello/controller/home/StartController.html#","e":false,"i":"","n":"StartController","t":"StartController extends Controller","d":"scothello.controller.home","k":"trait","x":""},
{"l":"scothello/controller/home/StartController.html#startGame-fffffa34","e":false,"i":"","n":"startGame","t":"startGame(usernames: Pair[String]): Unit","d":"scothello.controller.home.StartController","k":"def","x":""},
{"l":"scothello/controller/home/StartController$.html#","e":false,"i":"","n":"StartController","t":"StartController","d":"scothello.controller.home","k":"object","x":""},
{"l":"scothello/controller/home/StartController$.html#apply-fffff7d9","e":false,"i":"","n":"apply","t":"apply(requirements: Requirements[StartView]): StartController","d":"scothello.controller.home.StartController","k":"def","x":""},
{"l":"scothello/controller/BaseController.html#","e":false,"i":"","n":"BaseController","t":"BaseController[V <: View](requirements: Requirements[V]) extends Controller, Dependencies[V]","d":"scothello.controller","k":"class","x":""},
{"l":"scothello/controller/BaseController.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.controller.BaseController","k":"val","x":""},
{"l":"scothello/controller/Controller.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"scothello.controller","k":"trait","x":""},
{"l":"scothello/controller/Controller.html#state-0","e":false,"i":"","n":"state","t":"state: GameState","d":"scothello.controller.Controller","k":"def","x":""},
{"l":"scothello/controller/Controller$.html#","e":false,"i":"","n":"Controller","t":"Controller","d":"scothello.controller","k":"object","x":""},
{"l":"scothello/controller/Controller$.html#Factory-0","e":false,"i":"","n":"Factory","t":"Factory[V <: View, C <: Controller] = Requirements[V] => C","d":"scothello.controller.Controller","k":"type","x":""},
{"l":"scothello/controller/Controller$$Dependencies.html#","e":false,"i":"","n":"Dependencies","t":"Dependencies[V <: View](requirements: Requirements[V]) extends Controller","d":"scothello.controller.Controller","k":"trait","x":""},
{"l":"scothello/controller/Controller$$Dependencies.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.controller.Controller.Dependencies","k":"def","x":""},
{"l":"scothello/controller/Controller$$Dependencies.html#view-0","e":false,"i":"","n":"view","t":"view: V","d":"scothello.controller.Controller.Dependencies","k":"def","x":""},
{"l":"scothello/controller/Controller$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider[C <: Controller]","d":"scothello.controller.Controller","k":"trait","x":""},
{"l":"scothello/controller/Controller$$Provider.html#controller-0","e":false,"i":"","n":"controller","t":"controller: C","d":"scothello.controller.Controller.Provider","k":"def","x":""},
{"l":"scothello/controller/Controller$$Requirements.html#","e":false,"i":"","n":"Requirements","t":"Requirements[V <: View] extends Provider, Provider[V]","d":"scothello.controller.Controller","k":"trait","x":""},
{"l":"scothello/controller/EmptyController.html#","e":false,"i":"","n":"EmptyController","t":"EmptyController[V <: View](requirements: Requirements[V]) extends BaseController[V]","d":"scothello.controller","k":"class","x":""},
{"l":"scothello/controller/ReactiveModelWrapper.html#","e":false,"i":"","n":"ReactiveModelWrapper","t":"ReactiveModelWrapper(view: => View, model: Model) extends Model","d":"scothello.controller","k":"class","x":""},
{"l":"scothello/game.html#","e":false,"i":"","n":"scothello.game","t":"scothello.game","d":"","k":"package","x":""},
{"l":"scothello/game/manager.html#","e":false,"i":"","n":"scothello.game.manager","t":"scothello.game.manager","d":"","k":"package","x":""},
{"l":"scothello/game/manager/ScothelloFXApp$.html#","e":false,"i":"","n":"ScothelloFXApp","t":"ScothelloFXApp extends JFXApp3","d":"scothello.game.manager","k":"object","x":""},
{"l":"scothello/game/manager/ScothelloFXApp$.html#navigateTo-f9b","e":false,"i":"","n":"navigateTo","t":"navigateTo(page: Pages): Unit","d":"scothello.game.manager.ScothelloFXApp","k":"def","x":""},
{"l":"scothello/game/manager/ScothelloFXApp$.html#rootScene-0","e":false,"i":"","n":"rootScene","t":"rootScene: Scene","d":"scothello.game.manager.ScothelloFXApp","k":"val","x":""},
{"l":"scothello/game/manager/ScothelloGameManager$.html#","e":false,"i":"","n":"ScothelloGameManager","t":"ScothelloGameManager","d":"scothello.game.manager","k":"object","x":""},
{"l":"scothello/game/manager/ScothelloGameManager$.html#navigateTo-f9b","e":false,"i":"","n":"navigateTo","t":"navigateTo(page: Pages): Unit","d":"scothello.game.manager.ScothelloGameManager","k":"def","x":""},
{"l":"scothello/game/manager/ScothelloGameManager$.html#startGame-94c","e":false,"i":"","n":"startGame","t":"startGame(): Unit","d":"scothello.game.manager.ScothelloGameManager","k":"def","x":""},
{"l":"scothello/game/pages.html#","e":false,"i":"","n":"scothello.game.pages","t":"scothello.game.pages","d":"","k":"package","x":""},
{"l":"scothello/game/pages.html#rootScene-0","e":false,"i":"","n":"rootScene","t":"rootScene: Scene","d":"scothello.game.pages","k":"given","x":""},
{"l":"scothello/game/pages/GamePage.html#","e":false,"i":"","n":"GamePage","t":"GamePage[C <: Controller, V <: View](val model: Model, val pageFactory: PageFactory[C, V]) extends Requirements, Requirements[C], Requirements[V]","d":"scothello.game.pages","k":"trait","x":""},
{"l":"scothello/game/pages/GamePage.html#controller-0","e":false,"i":"","n":"controller","t":"controller: C","d":"scothello.game.pages.GamePage","k":"val","x":""},
{"l":"scothello/game/pages/GamePage.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.game.pages.GamePage","k":"val","x":""},
{"l":"scothello/game/pages/GamePage.html#pageFactory-0","e":false,"i":"","n":"pageFactory","t":"pageFactory: PageFactory[C, V]","d":"scothello.game.pages.GamePage","k":"val","x":""},
{"l":"scothello/game/pages/GamePage.html#view-0","e":false,"i":"","n":"view","t":"view: V","d":"scothello.game.pages.GamePage","k":"val","x":""},
{"l":"scothello/game/pages/GamePage$.html#","e":false,"i":"","n":"GamePage","t":"GamePage","d":"scothello.game.pages","k":"object","x":""},
{"l":"scothello/game/pages/GamePage$.html#apply-4ef","e":false,"i":"","n":"apply","t":"apply[C <: Controller, V <: View](model: Model, pageFactory: PageFactory[C, V]): GamePage[C, V]","d":"scothello.game.pages.GamePage","k":"def","x":""},
{"l":"scothello/game/pages/PageFactory.html#","e":false,"i":"","n":"PageFactory","t":"PageFactory[C <: Controller, V <: View]","d":"scothello.game.pages","k":"trait","x":""},
{"l":"scothello/game/pages/PageFactory.html#controllerFactory-0","e":false,"i":"","n":"controllerFactory","t":"controllerFactory: V => C","d":"scothello.game.pages.PageFactory","k":"def","x":""},
{"l":"scothello/game/pages/PageFactory.html#viewFactory-0","e":false,"i":"","n":"viewFactory","t":"viewFactory: C => V","d":"scothello.game.pages.PageFactory","k":"def","x":""},
{"l":"scothello/game/pages/PageFactory$.html#","e":false,"i":"","n":"PageFactory","t":"PageFactory","d":"scothello.game.pages","k":"object","x":""},
{"l":"scothello/game/pages/PageFactory$.html#apply-fffff118","e":false,"i":"","n":"apply","t":"apply[C <: Controller, V <: View](_viewFactory: C => V, _controllerFactory: V => C): PageFactory[C, V]","d":"scothello.game.pages.PageFactory","k":"def","x":""},
{"l":"scothello/game/pages/Pages.html#","e":false,"i":"","n":"Pages","t":"Pages(val pageFactory: PageFactory[_, _])","d":"scothello.game.pages","k":"enum","x":""},
{"l":"scothello/game/pages/Pages.html#Home-0","e":false,"i":"","n":"Home","t":"Home extends Pages","d":"scothello.game.pages.Pages","k":"case","x":""},
{"l":"scothello/game/pages/Pages.html#Start-0","e":false,"i":"","n":"Start","t":"Start extends Pages","d":"scothello.game.pages.Pages","k":"case","x":""},
{"l":"scothello/game/pages/Pages.html#Game-0","e":false,"i":"","n":"Game","t":"Game extends Pages","d":"scothello.game.pages.Pages","k":"case","x":""},
{"l":"scothello/game/pages/ScalaFXPageFactory$.html#","e":false,"i":"","n":"ScalaFXPageFactory","t":"ScalaFXPageFactory","d":"scothello.game.pages","k":"object","x":""},
{"l":"scothello/game/pages/ScalaFXPageFactory$.html#apply-fffff2a9","e":false,"i":"","n":"apply","t":"apply[C <: Controller, V <: View](scalaFXViewFactory: C => V, _controllerFactory: V => C)(using rootScene: Scene): PageFactory[C, V]","d":"scothello.game.pages.ScalaFXPageFactory","k":"def","x":""},
{"l":"scothello/game/ScothelloGame.html#","e":false,"i":"","n":"ScothelloGame","t":"ScothelloGame","d":"scothello.game","k":"trait","x":""},
{"l":"scothello/game/ScothelloGame.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.game.ScothelloGame","k":"val","x":""},
{"l":"scothello/game/ScothelloGame.html#pages-0","e":false,"i":"","n":"pages","t":"pages: Map[Pages, GamePage[_, _]]","d":"scothello.game.ScothelloGame","k":"val","x":""},
{"l":"scothello/game/ScothelloGame$.html#","e":false,"i":"","n":"ScothelloGame","t":"ScothelloGame","d":"scothello.game","k":"object","x":""},
{"l":"scothello/game/ScothelloGame$.html#apply-d2c","e":false,"i":"","n":"apply","t":"apply(pagesFactories: Map[Pages, PageFactory[_, _]]): ScothelloGame","d":"scothello.game.ScothelloGame","k":"def","x":""},
{"l":"scothello/model.html#","e":false,"i":"","n":"scothello.model","t":"scothello.model","d":"","k":"package","x":""},
{"l":"scothello/model/board.html#","e":false,"i":"","n":"scothello.model.board","t":"scothello.model.board","d":"","k":"package","x":""},
{"l":"scothello/model/board.html#AllowedTiles-0","e":false,"i":"","n":"AllowedTiles","t":"AllowedTiles = Map[Tile, Player]","d":"scothello.model.board","k":"type","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#","e":false,"i":"","n":"AllowedTiles","t":"AllowedTiles","d":"scothello.model.board","k":"object","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#calculate-fffffbf7","e":false,"i":"","n":"calculate","t":"calculate(player: Player, assignedPawns: AssignedPawns): AllowedTiles","d":"scothello.model.board.AllowedTiles","k":"def","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#checkIfAvailableMoves-538","e":false,"i":"","n":"checkIfAvailableMoves","t":"checkIfAvailableMoves(allowedTiles: AllowedTiles): Boolean","d":"scothello.model.board.AllowedTiles","k":"def","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: AllowedTiles","d":"scothello.model.board.AllowedTiles","k":"def","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#flipsMap-0","e":false,"i":"","n":"flipsMap","t":"flipsMap: Map[Tile, ArrayBuffer[Tile]]","d":"scothello.model.board.AllowedTiles","k":"val","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#initial-fffffbf7","e":false,"i":"","n":"initial","t":"initial(player: Player, assignedPawns: AssignedPawns): AllowedTiles","d":"scothello.model.board.AllowedTiles","k":"def","x":""},
{"l":"scothello/model/board/AllowedTiles$.html#resetMap-94c","e":false,"i":"","n":"resetMap","t":"resetMap(): Unit","d":"scothello.model.board.AllowedTiles","k":"def","x":""},
{"l":"scothello/model/board/Board.html#","e":false,"i":"","n":"Board","t":"Board(rows: Int, cols: Int) extends TiledBoard","d":"scothello.model.board","k":"class","x":""},
{"l":"scothello/model/board/Board.html#centralTiles-0","e":false,"i":"","n":"centralTiles","t":"centralTiles: CentralTiles","d":"scothello.model.board.Board","k":"val","x":""},
{"l":"scothello/model/board/CentralTiles.html#","e":false,"i":"","n":"CentralTiles","t":"CentralTiles(upperLeft: Tile, upperRight: Tile, lowerLeft: Tile, lowerRight: Tile)","d":"scothello.model.board","k":"class","x":""},
{"l":"scothello/model/board/Tile.html#","e":false,"i":"","n":"Tile","t":"Tile","d":"scothello.model.board","k":"trait","x":""},
{"l":"scothello/model/board/Tile.html#col-0","e":false,"i":"","n":"col","t":"col: Int","d":"scothello.model.board.Tile","k":"def","x":""},
{"l":"scothello/model/board/Tile.html#row-0","e":false,"i":"","n":"row","t":"row: Int","d":"scothello.model.board.Tile","k":"def","x":""},
{"l":"scothello/model/board/Tile$.html#","e":false,"i":"","n":"Tile","t":"Tile","d":"scothello.model.board","k":"object","x":""},
{"l":"scothello/model/board/Tile$.html#apply-fffff0ac","e":false,"i":"","n":"apply","t":"apply(row: Int, col: Int): Tile","d":"scothello.model.board.Tile","k":"def","x":""},
{"l":"scothello/model/board/TiledBoard.html#","e":false,"i":"","n":"TiledBoard","t":"TiledBoard(val rows: Int, val cols: Int)","d":"scothello.model.board","k":"class","x":""},
{"l":"scothello/model/board/TiledBoard.html#cols-0","e":false,"i":"","n":"cols","t":"cols: Int","d":"scothello.model.board.TiledBoard","k":"val","x":""},
{"l":"scothello/model/board/TiledBoard.html#rows-0","e":false,"i":"","n":"rows","t":"rows: Int","d":"scothello.model.board.TiledBoard","k":"val","x":""},
{"l":"scothello/model/board/TiledBoard.html#tiles-0","e":false,"i":"","n":"tiles","t":"tiles: Set[Tile]","d":"scothello.model.board.TiledBoard","k":"val","x":""},
{"l":"scothello/model/components.html#","e":false,"i":"","n":"scothello.model.components","t":"scothello.model.components","d":"","k":"package","x":""},
{"l":"scothello/model/components.html#AssignedPawns-0","e":false,"i":"","n":"AssignedPawns","t":"AssignedPawns = Map[Tile, Pawn]","d":"scothello.model.components","k":"type","x":""},
{"l":"scothello/model/components.html#Scores-0","e":false,"i":"","n":"Scores","t":"Scores = Map[Player, Int]","d":"scothello.model.components","k":"type","x":""},
{"l":"scothello/model/components/AssignedPawns$.html#","e":false,"i":"","n":"AssignedPawns","t":"AssignedPawns","d":"scothello.model.components","k":"object","x":""},
{"l":"scothello/model/components/AssignedPawns$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: AssignedPawns","d":"scothello.model.components.AssignedPawns","k":"def","x":""},
{"l":"scothello/model/components/AssignedPawns$.html#initial-4be","e":false,"i":"","n":"initial","t":"initial(players: Pair[Player], centralTiles: CentralTiles): AssignedPawns","d":"scothello.model.components.AssignedPawns","k":"def","x":""},
{"l":"scothello/model/components/Pawn.html#","e":false,"i":"","n":"Pawn","t":"Pawn","d":"scothello.model.components","k":"trait","x":""},
{"l":"scothello/model/components/Pawn.html#player-0","e":false,"i":"","n":"player","t":"player: Player","d":"scothello.model.components.Pawn","k":"def","x":""},
{"l":"scothello/model/components/Pawn$.html#","e":false,"i":"","n":"Pawn","t":"Pawn","d":"scothello.model.components","k":"object","x":""},
{"l":"scothello/model/components/Pawn$.html#apply-d43","e":false,"i":"","n":"apply","t":"apply(player: Player): Pawn","d":"scothello.model.components.Pawn","k":"def","x":""},
{"l":"scothello/model/components/Scores$.html#","e":false,"i":"","n":"Scores","t":"Scores","d":"scothello.model.components","k":"object","x":""},
{"l":"scothello/model/components/Scores$.html#calculateScores-50","e":false,"i":"","n":"calculateScores","t":"calculateScores(assignedPawns: AssignedPawns): Scores","d":"scothello.model.components.Scores","k":"def","x":""},
{"l":"scothello/model/components/Scores$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Scores","d":"scothello.model.components.Scores","k":"def","x":""},
{"l":"scothello/model/game.html#","e":false,"i":"","n":"scothello.model.game","t":"scothello.model.game","d":"","k":"package","x":""},
{"l":"scothello/model/game/config.html#","e":false,"i":"","n":"scothello.model.game.config","t":"scothello.model.game.config","d":"","k":"package","x":""},
{"l":"scothello/model/game/config/Player.html#","e":false,"i":"","n":"Player","t":"Player","d":"scothello.model.game.config","k":"trait","x":""},
{"l":"scothello/model/game/config/Player.html#color-0","e":false,"i":"","n":"color","t":"color: PlayerColor","d":"scothello.model.game.config.Player","k":"def","x":""},
{"l":"scothello/model/game/config/Player.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"scothello.model.game.config.Player","k":"def","x":""},
{"l":"scothello/model/game/config/Player$.html#","e":false,"i":"","n":"Player","t":"Player","d":"scothello.model.game.config","k":"object","x":""},
{"l":"scothello/model/game/config/Player$.html#apply-3de","e":false,"i":"","n":"apply","t":"apply(name: String, color: PlayerColor): Player","d":"scothello.model.game.config.Player","k":"def","x":""},
{"l":"scothello/model/game/config/Player$.html#apply-fffff54c","e":false,"i":"","n":"apply","t":"apply(name: String): Player","d":"scothello.model.game.config.Player","k":"def","x":""},
{"l":"scothello/model/game/config/Player$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Player","d":"scothello.model.game.config.Player","k":"val","x":""},
{"l":"scothello/model/game/config/PlayerColor.html#","e":false,"i":"","n":"PlayerColor","t":"PlayerColor","d":"scothello.model.game.config","k":"enum","x":""},
{"l":"scothello/model/game/config/PlayerColor.html#Black-0","e":false,"i":"","n":"Black","t":"Black extends PlayerColor","d":"scothello.model.game.config.PlayerColor","k":"case","x":""},
{"l":"scothello/model/game/config/PlayerColor.html#White-0","e":false,"i":"","n":"White","t":"White extends PlayerColor","d":"scothello.model.game.config.PlayerColor","k":"case","x":""},
{"l":"scothello/model/game/config/PlayerColor.html#NoColor-0","e":false,"i":"","n":"NoColor","t":"NoColor extends PlayerColor","d":"scothello.model.game.config.PlayerColor","k":"case","x":""},
{"l":"scothello/model/game/state.html#","e":false,"i":"","n":"scothello.model.game.state","t":"scothello.model.game.state","d":"","k":"package","x":""},
{"l":"scothello/model/game/state/ops.html#","e":false,"i":"","n":"scothello.model.game.state.ops","t":"scothello.model.game.state.ops","d":"","k":"package","x":""},
{"l":"scothello/model/game/state/ops/GameOps$.html#","e":false,"i":"","n":"GameOps","t":"GameOps","d":"scothello.model.game.state.ops","k":"object","x":""},
{"l":"scothello/model/game/state/ops/GameOps$.html#calculateAllowedPos-fffff939","e":false,"i":"extension (state: GameState)","n":"calculateAllowedPos","t":"calculateAllowedPos(): Option[GameState]","d":"scothello.model.game.state.ops.GameOps","k":"def","x":""},
{"l":"scothello/model/game/state/ops/GameOps$.html#flipPawns-105","e":false,"i":"extension (state: GameState)","n":"flipPawns","t":"flipPawns(tile: Tile): Option[GameState]","d":"scothello.model.game.state.ops.GameOps","k":"def","x":""},
{"l":"scothello/model/game/state/ops/GameOps$.html#nextTurn-fffff939","e":false,"i":"extension (state: GameState)","n":"nextTurn","t":"nextTurn(): Option[GameState]","d":"scothello.model.game.state.ops.GameOps","k":"def","x":""},
{"l":"scothello/model/game/state/ops/GameOps$.html#placePawn-105","e":false,"i":"extension (state: GameState)","n":"placePawn","t":"placePawn(tile: Tile): Option[GameState]","d":"scothello.model.game.state.ops.GameOps","k":"def","x":""},
{"l":"scothello/model/game/state/ops/StartOps$.html#","e":false,"i":"","n":"StartOps","t":"StartOps","d":"scothello.model.game.state.ops","k":"object","x":""},
{"l":"scothello/model/game/state/ops/StartOps$.html#startGame-fffffa21","e":false,"i":"extension (state: GameState)","n":"startGame","t":"startGame(usernames: Pair[String]): Option[GameState]","d":"scothello.model.game.state.ops.StartOps","k":"def","x":""},
{"l":"scothello/model/game/state/GameState.html#","e":false,"i":"","n":"GameState","t":"GameState(players: Pair[Player], board: Board, assignedPawns: AssignedPawns, allowedTiles: AllowedTiles, turn: Turn, playerScores: Scores, isOver: Boolean, winner: Option[Player])","d":"scothello.model.game.state","k":"class","x":""},
{"l":"scothello/model/game/state/GameState$.html#","e":false,"i":"","n":"GameState","t":"GameState","d":"scothello.model.game.state","k":"object","x":""},
{"l":"scothello/model/game/state/GameState$.html#apply-cfc","e":false,"i":"","n":"apply","t":"apply(): GameState","d":"scothello.model.game.state.GameState","k":"def","x":""},
{"l":"scothello/model/game/Turn.html#","e":false,"i":"","n":"Turn","t":"Turn","d":"scothello.model.game","k":"trait","x":""},
{"l":"scothello/model/game/Turn.html#number-0","e":false,"i":"","n":"number","t":"number: Int","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn.html#player-0","e":false,"i":"","n":"player","t":"player: Player","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$.html#","e":false,"i":"","n":"Turn","t":"Turn","d":"scothello.model.game","k":"object","x":""},
{"l":"scothello/model/game/Turn$.html#apply-495","e":false,"i":"","n":"apply","t":"apply(number: Int, player: Player): Turn","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Turn","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$.html#initial-81c","e":false,"i":"","n":"initial","t":"initial(player: Player): Turn","d":"scothello.model.game.Turn","k":"def","x":""},
{"l":"scothello/model/game/Turn$$Empty.html#","e":false,"i":"","n":"Empty","t":"Empty extends Turn","d":"scothello.model.game.Turn","k":"trait","x":""},
{"l":"scothello/model/game/Turn$$Empty.html#number-0","e":false,"i":"","n":"number","t":"number: Int","d":"scothello.model.game.Turn.Empty","k":"def","x":""},
{"l":"scothello/model/game/Turn$$Empty.html#player-0","e":false,"i":"","n":"player","t":"player: Player","d":"scothello.model.game.Turn.Empty","k":"def","x":""},
{"l":"scothello/model/game/Turn$$EmptyTurn$.html#","e":false,"i":"","n":"EmptyTurn","t":"EmptyTurn extends Empty","d":"scothello.model.game.Turn","k":"object","x":""},
{"l":"scothello/model/game/Turn$$ValidTurn.html#","e":false,"i":"","n":"ValidTurn","t":"ValidTurn(number: Int, player: Player) extends Turn","d":"scothello.model.game.Turn","k":"class","x":""},
{"l":"scothello/model/game/TurnManager$.html#","e":false,"i":"","n":"TurnManager","t":"TurnManager","d":"scothello.model.game","k":"object","x":""},
{"l":"scothello/model/game/TurnManager$.html#apply-fffffa34","e":false,"i":"","n":"apply","t":"apply(players: Pair[Player]): Unit","d":"scothello.model.game.TurnManager","k":"def","x":""},
{"l":"scothello/model/game/TurnManager$.html#initialTurn-0","e":false,"i":"","n":"initialTurn","t":"initialTurn: Turn","d":"scothello.model.game.TurnManager","k":"def","x":""},
{"l":"scothello/model/game/TurnManager$.html#nextTurn-0","e":false,"i":"","n":"nextTurn","t":"nextTurn: Turn","d":"scothello.model.game.TurnManager","k":"def","x":""},
{"l":"scothello/model/Model.html#","e":false,"i":"","n":"Model","t":"Model","d":"scothello.model","k":"trait","x":""},
{"l":"scothello/model/Model.html#state-0","e":false,"i":"","n":"state","t":"state: GameState","d":"scothello.model.Model","k":"def","x":""},
{"l":"scothello/model/Model.html#update-c9d","e":false,"i":"","n":"update","t":"update(u: GameState => GameState): Unit","d":"scothello.model.Model","k":"def","x":""},
{"l":"scothello/model/Model$.html#","e":false,"i":"","n":"Model","t":"Model","d":"scothello.model","k":"object","x":""},
{"l":"scothello/model/Model$.html#apply-5d7","e":false,"i":"","n":"apply","t":"apply(initialState: GameState): Model","d":"scothello.model.Model","k":"def","x":""},
{"l":"scothello/model/Model$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider","d":"scothello.model.Model","k":"trait","x":""},
{"l":"scothello/model/Model$$Provider.html#model-0","e":false,"i":"","n":"model","t":"model: Model","d":"scothello.model.Model.Provider","k":"def","x":""},
{"l":"scothello/model/Model$$Requirements.html#","e":false,"i":"","n":"Requirements","t":"Requirements","d":"scothello.model.Model","k":"trait","x":""},
{"l":"scothello/model/ModelOps$.html#","e":false,"i":"","n":"ModelOps","t":"ModelOps","d":"scothello.model","k":"object","x":""},
{"l":"scothello/model/ModelOps$.html#onError-23f","e":false,"i":"extension (state: Option[GameState])","n":"onError","t":"onError(callback: => Unit): Unit","d":"scothello.model.ModelOps","k":"def","x":""},
{"l":"scothello/model/ModelOps$.html#updateState-fffff01b","e":false,"i":"extension (model: Model)","n":"updateState","t":"updateState(update: GameState => Option[GameState]): Option[GameState]","d":"scothello.model.ModelOps","k":"def","x":""},
{"l":"scothello/utils.html#","e":false,"i":"","n":"scothello.utils","t":"scothello.utils","d":"","k":"package","x":""},
{"l":"scothello/utils/Pair.html#","e":false,"i":"","n":"Pair","t":"Pair[A](_1: A, _2: A)","d":"scothello.utils","k":"class","x":""},
{"l":"scothello/utils/Pair.html#find-94e","e":false,"i":"","n":"find","t":"find(predicate: A => Boolean): Option[A]","d":"scothello.utils.Pair","k":"def","x":""},
{"l":"scothello/utils/Pair.html#map-66b","e":false,"i":"","n":"map","t":"map[B](f: A => B): Seq[B]","d":"scothello.utils.Pair","k":"def","x":""},
{"l":"scothello/utils/Pair$.html#","e":false,"i":"","n":"Pair","t":"Pair","d":"scothello.utils","k":"object","x":""},
{"l":"scothello/utils/Pair$.html#fromSeq-fffffb84","e":false,"i":"","n":"fromSeq","t":"fromSeq[A](seq: Seq[A]): Pair[A]","d":"scothello.utils.Pair","k":"def","x":""},
{"l":"scothello/utils/Pair$.html#tupleToPair-fffff14b","e":false,"i":"","n":"tupleToPair","t":"tupleToPair[A](tuple: (A, A)): Pair[A]","d":"scothello.utils.Pair","k":"def","x":""},
{"l":"scothello/view.html#","e":false,"i":"","n":"scothello.view","t":"scothello.view","d":"","k":"package","x":""},
{"l":"scothello/view/game.html#","e":false,"i":"","n":"scothello.view.game","t":"scothello.view.game","d":"","k":"package","x":""},
{"l":"scothello/view/game/components.html#","e":false,"i":"","n":"scothello.view.game.components","t":"scothello.view.game.components","d":"","k":"package","x":""},
{"l":"scothello/view/game/components/BoardComponent$.html#","e":false,"i":"","n":"BoardComponent","t":"BoardComponent","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/BoardComponent$.html#boardComponent-fffff03c","e":false,"i":"","n":"boardComponent","t":"boardComponent(topComponentHeights: Double*)(using displayScene: Scene, reactiveGameState: ObjectProperty[GameState], clickHandler: GameViewClickHandler, gameController: GameController): HBox","d":"scothello.view.game.components.BoardComponent","k":"def","x":""},
{"l":"scothello/view/game/components/Clock$.html#","e":false,"i":"","n":"Clock","t":"Clock","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/Clock$.html#curTime-0","e":false,"i":"","n":"curTime","t":"curTime: StringProperty","d":"scothello.view.game.components.Clock","k":"val","x":""},
{"l":"scothello/view/game/components/ClockComponent$.html#","e":false,"i":"","n":"ClockComponent","t":"ClockComponent","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/ClockComponent$.html#clockComponent-9ed","e":false,"i":"","n":"clockComponent","t":"clockComponent(using displayScene: Scene): VBox","d":"scothello.view.game.components.ClockComponent","k":"def","x":""},
{"l":"scothello/view/game/components/GameViewClickHandler.html#","e":false,"i":"","n":"GameViewClickHandler","t":"GameViewClickHandler","d":"scothello.view.game.components","k":"trait","x":""},
{"l":"scothello/view/game/components/GameViewClickHandler.html#onTileClick-718","e":false,"i":"","n":"onTileClick","t":"onTileClick(tile: Tile): Unit","d":"scothello.view.game.components.GameViewClickHandler","k":"def","x":""},
{"l":"scothello/view/game/components/GameViewClickHandler$.html#","e":false,"i":"","n":"GameViewClickHandler","t":"GameViewClickHandler","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/GameViewClickHandler$.html#apply-fffff244","e":false,"i":"","n":"apply","t":"apply(gameController: GameController): GameViewClickHandler","d":"scothello.view.game.components.GameViewClickHandler","k":"def","x":""},
{"l":"scothello/view/game/components/HeaderComponent$.html#","e":false,"i":"","n":"HeaderComponent","t":"HeaderComponent","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/HeaderComponent$.html#headerComponent-fffff21e","e":false,"i":"","n":"headerComponent","t":"headerComponent(headerHeight: Double)(using displayScene: Scene, reactiveGameState: ObjectProperty[GameState]): HBox","d":"scothello.view.game.components.HeaderComponent","k":"def","x":""},
{"l":"scothello/view/game/components/NotificationsBarComponent$.html#","e":false,"i":"","n":"NotificationsBarComponent","t":"NotificationsBarComponent","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/NotificationsBarComponent$.html#notificationsBarComponent-fffff21e","e":false,"i":"","n":"notificationsBarComponent","t":"notificationsBarComponent(notificationsBarHeight: Double)(using displayScene: Scene, reactiveGameState: ObjectProperty[GameState]): HBox","d":"scothello.view.game.components.NotificationsBarComponent","k":"def","x":""},
{"l":"scothello/view/game/components/PlayerComponent$.html#","e":false,"i":"","n":"PlayerComponent","t":"PlayerComponent","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/PlayerComponent$.html#playerComponent-e82","e":false,"i":"","n":"playerComponent","t":"playerComponent(player: Player)(using displayScene: Scene, reactiveGameState: ObjectProperty[GameState]): VBox","d":"scothello.view.game.components.PlayerComponent","k":"def","x":""},
{"l":"scothello/view/game/components/StopButtonComponent$.html#","e":false,"i":"","n":"StopButtonComponent","t":"StopButtonComponent","d":"scothello.view.game.components","k":"object","x":""},
{"l":"scothello/view/game/components/StopButtonComponent$.html#stopButtonComponent-d12","e":false,"i":"","n":"stopButtonComponent","t":"stopButtonComponent(using displayScene: Scene, gameController: GameController): HBox","d":"scothello.view.game.components.StopButtonComponent","k":"def","x":""},
{"l":"scothello/view/game/GameView.html#","e":false,"i":"","n":"GameView","t":"GameView extends View","d":"scothello.view.game","k":"trait","x":""},
{"l":"scothello/view/game/GameView$.html#","e":false,"i":"","n":"GameView","t":"GameView","d":"scothello.view.game","k":"object","x":""},
{"l":"scothello/view/game/GameView$.html#apply-fffff15e","e":false,"i":"","n":"apply","t":"apply(scene: Scene, requirements: Requirements[GameController]): GameView","d":"scothello.view.game.GameView","k":"def","x":""},
{"l":"scothello/view/home.html#","e":false,"i":"","n":"scothello.view.home","t":"scothello.view.home","d":"","k":"package","x":""},
{"l":"scothello/view/home/HomeView.html#","e":false,"i":"","n":"HomeView","t":"HomeView extends View","d":"scothello.view.home","k":"trait","x":""},
{"l":"scothello/view/home/HomeView$.html#","e":false,"i":"","n":"HomeView","t":"HomeView","d":"scothello.view.home","k":"object","x":""},
{"l":"scothello/view/home/HomeView$.html#apply-d7e","e":false,"i":"","n":"apply","t":"apply(scene: Scene, requirements: Requirements[HomeController]): HomeView","d":"scothello.view.home.HomeView","k":"def","x":""},
{"l":"scothello/view/home/StartView.html#","e":false,"i":"","n":"StartView","t":"StartView extends View","d":"scothello.view.home","k":"trait","x":""},
{"l":"scothello/view/home/StartView$.html#","e":false,"i":"","n":"StartView","t":"StartView","d":"scothello.view.home","k":"object","x":""},
{"l":"scothello/view/home/StartView$.html#apply-fffffc0d","e":false,"i":"","n":"apply","t":"apply(scene: Scene, requirements: Requirements[StartController]): StartView","d":"scothello.view.home.StartView","k":"def","x":""},
{"l":"scothello/view/utils.html#","e":false,"i":"","n":"scothello.view.utils","t":"scothello.view.utils","d":"","k":"package","x":""},
{"l":"scothello/view/utils/ColorMapper$.html#","e":false,"i":"","n":"ColorMapper","t":"ColorMapper","d":"scothello.view.utils","k":"object","x":""},
{"l":"scothello/view/utils/ColorMapper$.html#toFxColor-fffff77f","e":false,"i":"","n":"toFxColor","t":"toFxColor(playerColor: PlayerColor): Color","d":"scothello.view.utils.ColorMapper","k":"def","x":""},
{"l":"scothello/view/utils/ReactiveStateUtils$.html#","e":false,"i":"","n":"ReactiveStateUtils","t":"ReactiveStateUtils","d":"scothello.view.utils","k":"object","x":""},
{"l":"scothello/view/utils/ReactiveStateUtils$.html#getPlayerColor-57d","e":false,"i":"","n":"getPlayerColor","t":"getPlayerColor(reactiveState: ObjectProperty[GameState], player: Player): ObservableValue[PlayerColor, PlayerColor]","d":"scothello.view.utils.ReactiveStateUtils","k":"def","x":""},
{"l":"scothello/view/BaseScalaFXView.html#","e":false,"i":"","n":"BaseScalaFXView","t":"BaseScalaFXView[C <: Controller](scene: Scene, requirements: Requirements[C]) extends BaseView[C], ScalaFXView","d":"scothello.view","k":"class","x":""},
{"l":"scothello/view/BaseView.html#","e":false,"i":"","n":"BaseView","t":"BaseView[C <: Controller](val requirements: Requirements[C]) extends View, NavigatorView, Dependencies[C]","d":"scothello.view","k":"class","x":""},
{"l":"scothello/view/BaseView.html#requirements-0","e":false,"i":"","n":"requirements","t":"requirements: Requirements[C]","d":"scothello.view.BaseView","k":"val","x":""},
{"l":"scothello/view/NavigatorView.html#","e":false,"i":"","n":"NavigatorView","t":"NavigatorView extends View","d":"scothello.view","k":"trait","x":""},
{"l":"scothello/view/NavigatorView.html#navigateTo-f9b","e":false,"i":"","n":"navigateTo","t":"navigateTo(page: Pages): Unit","d":"scothello.view.NavigatorView","k":"def","x":""},
{"l":"scothello/view/ScalaFXView.html#","e":false,"i":"","n":"ScalaFXView","t":"ScalaFXView(val scene: Scene) extends View","d":"scothello.view","k":"trait","x":""},
{"l":"scothello/view/ScalaFXView.html#parent-0","e":false,"i":"","n":"parent","t":"parent: Parent","d":"scothello.view.ScalaFXView","k":"def","x":""},
{"l":"scothello/view/ScalaFXView.html#reactiveState-0","e":false,"i":"","n":"reactiveState","t":"reactiveState: ObjectProperty[GameState]","d":"scothello.view.ScalaFXView","k":"def","x":""},
{"l":"scothello/view/ScalaFXView.html#scene-0","e":false,"i":"","n":"scene","t":"scene: Scene","d":"scothello.view.ScalaFXView","k":"val","x":""},
{"l":"scothello/view/ScalaFXView$.html#","e":false,"i":"","n":"ScalaFXView","t":"ScalaFXView","d":"scothello.view","k":"object","x":""},
{"l":"scothello/view/ScalaFXView$.html#Factory-0","e":false,"i":"","n":"Factory","t":"Factory[C <: Controller, V <: View] = (Scene, Requirements[C]) => V","d":"scothello.view.ScalaFXView","k":"type","x":""},
{"l":"scothello/view/View.html#","e":false,"i":"","n":"View","t":"View","d":"scothello.view","k":"trait","x":""},
{"l":"scothello/view/View.html#hide-94c","e":false,"i":"","n":"hide","t":"hide(): Unit","d":"scothello.view.View","k":"def","x":""},
{"l":"scothello/view/View.html#show-94c","e":false,"i":"","n":"show","t":"show(): Unit","d":"scothello.view.View","k":"def","x":""},
{"l":"scothello/view/View.html#state-0","e":false,"i":"","n":"state","t":"state: GameState","d":"scothello.view.View","k":"def","x":""},
{"l":"scothello/view/View.html#updateState-b48","e":false,"i":"","n":"updateState","t":"updateState(state: GameState): Unit","d":"scothello.view.View","k":"def","x":""},
{"l":"scothello/view/View$.html#","e":false,"i":"","n":"View","t":"View","d":"scothello.view","k":"object","x":""},
{"l":"scothello/view/View$.html#Factory-0","e":false,"i":"","n":"Factory","t":"Factory[C <: Controller, V <: View] = Requirements[C] => V","d":"scothello.view.View","k":"type","x":""},
{"l":"scothello/view/View$$Dependencies.html#","e":false,"i":"","n":"Dependencies","t":"Dependencies[C <: Controller](requirements: Requirements[C]) extends View","d":"scothello.view.View","k":"trait","x":""},
{"l":"scothello/view/View$$Dependencies.html#controller-0","e":false,"i":"","n":"controller","t":"controller: C","d":"scothello.view.View.Dependencies","k":"def","x":""},
{"l":"scothello/view/View$$Provider.html#","e":false,"i":"","n":"Provider","t":"Provider[V <: View]","d":"scothello.view.View","k":"trait","x":""},
{"l":"scothello/view/View$$Provider.html#view-0","e":false,"i":"","n":"view","t":"view: V","d":"scothello.view.View.Provider","k":"def","x":""},
{"l":"scothello/view/View$$Requirements.html#","e":false,"i":"","n":"Requirements","t":"Requirements[C <: Controller] extends Provider[C]","d":"scothello.view.View","k":"trait","x":""},
{"l":"scothello/main.html#","e":false,"i":"","n":"main","t":"main","d":"scothello","k":"class","x":""}];